use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    // TAURI_CREATOR:SPECTA_MODULE_IMPORTS
    // TAURI_CREATOR:END_SPECTA_MODULE_IMPORTS

    Builder::<tauri::Wry>::new().commands(collect_commands![
        greet,
        // TAURI_CREATOR:SPECTA_COMMANDS
        // TAURI_CREATOR:END_SPECTA_COMMANDS
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
#[allow(dead_code)]
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/tauri-bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/tauri-bindings.ts");
    }
}
