import { mkdir, readFile, readdir, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const featuresDir = path.join(root, 'features')
const recipesDir = path.join(root, 'recipes')
const readmeRecipeStart = '<!-- TAURI_CREATOR:README_RECIPES_START -->'
const readmeRecipeEnd = '<!-- TAURI_CREATOR:README_RECIPES_END -->'

function fail(message) {
  console.error(`generate-docs: ${message}`)
  process.exit(1)
}

async function pathExists(filePath) {
  try {
    await stat(filePath)
    return true
  } catch (error) {
    if (error.code === 'ENOENT') return false
    throw error
  }
}

async function readJson(filePath) {
  const raw = await readFile(filePath, 'utf8')
  try {
    return JSON.parse(raw)
  } catch (error) {
    throw new Error(`${filePath}: invalid JSON (${error.message})`)
  }
}

async function loadFeatures() {
  const entries = await readdir(featuresDir, { withFileTypes: true })
  const features = []

  for (const entry of entries) {
    if (!entry.isDirectory()) continue

    const manifestPath = path.join(featuresDir, entry.name, 'feature.json')
    const manifest = await readJson(manifestPath)
    features.push({
      dir: path.join(featuresDir, entry.name),
      manifest,
    })
  }

  return features.sort((left, right) => left.manifest.name.localeCompare(right.manifest.name))
}

async function loadRecipes() {
  const entries = await readdir(recipesDir, { withFileTypes: true })
  const recipes = []
  const preferredOrder = new Map([
    ['minimal', 0],
    ['essential', 1],
    ['desktop', 2],
    ['production', 3],
  ])

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.json')) continue

    const recipePath = path.join(recipesDir, entry.name)
    recipes.push(await readJson(recipePath))
  }

  return recipes.sort((left, right) => {
    const leftOrder = preferredOrder.get(left.name) ?? Number.MAX_SAFE_INTEGER
    const rightOrder = preferredOrder.get(right.name) ?? Number.MAX_SAFE_INTEGER
    return leftOrder === rightOrder
      ? left.name.localeCompare(right.name)
      : leftOrder - rightOrder
  })
}

function resolveFeatureOrder(recipe, featureMap) {
  const resolved = []
  const visiting = new Set()
  const visited = new Set()

  function visit(featureName) {
    const manifest = featureMap.get(featureName)
    if (!manifest) {
      fail(`recipe '${recipe.name}' references unknown feature '${featureName}'`)
    }

    if (visiting.has(featureName)) {
      fail(`cyclic feature dependency involving '${featureName}'`)
    }

    if (visited.has(featureName)) return

    visiting.add(featureName)
    for (const dependency of manifest.dependsOn ?? []) {
      visit(dependency)
    }
    visiting.delete(featureName)

    visited.add(featureName)
    resolved.push(featureName)
  }

  for (const featureName of recipe.features ?? []) {
    visit(featureName)
  }

  return resolved
}

function escapeTableCell(value) {
  return String(value).replaceAll('|', '\\|').replace(/\s+/g, ' ').trim()
}

function formatCodeList(values) {
  if (!Array.isArray(values) || values.length === 0) return 'none'
  return values.map((value) => `\`${value}\``).join(', ')
}

function findDocsPath(files) {
  return (files ?? []).find((file) => file.startsWith('docs/features/') && file.endsWith('.md'))
}

function renderFeatureIndex(features) {
  const rows = features.map(({ manifest }) => {
    const docsPath = findDocsPath(manifest.files)
    return [
      `\`${manifest.name}\``,
      manifest.stage,
      escapeTableCell(manifest.description),
      formatCodeList(manifest.dependsOn),
      formatCodeList(manifest.tauriCommands),
      formatCodeList(manifest.capabilities),
      formatCodeList(manifest.qualityChecks),
      docsPath ? `\`${docsPath}\`` : 'none',
    ]
  })

  return `# Feature Matrix

Generated from \`features/*/feature.json\`. Do not edit this file by hand.

| Feature | Stage | Description | Dependencies | Tauri Commands | Capabilities | Quality Checks | Docs |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows.map((row) => `| ${row.join(' | ')} |`).join('\n')}
`
}

function renderRecipeIndex(recipes, featureMap) {
  const rows = recipes.map((recipe) => {
    const resolved = resolveFeatureOrder(recipe, featureMap)
    return [
      `\`${recipe.name}\``,
      escapeTableCell(recipe.description ?? ''),
      formatCodeList(recipe.features),
      formatCodeList(resolved),
    ]
  })

  return `# Recipe Matrix

Generated from the \`recipes/*.json\` ladder and feature dependency metadata. Do not edit this file by hand.

| Recipe | Description | Requested Features | Resolved Feature Order |
| --- | --- | --- | --- |
${rows.map((row) => `| ${row.join(' | ')} |`).join('\n')}
`
}

function formatReadmeFeatureList(values) {
  return values.length === 0 ? 'base only' : formatCodeList(values)
}

function renderReadmeRecipeList(recipes, featureMap) {
  const rows = recipes.map((recipe) => {
    const resolved = resolveFeatureOrder(recipe, featureMap)
    return `- \`${recipe.name}\`: ${recipe.description} Features: ${formatReadmeFeatureList(resolved)}.`
  })

  return `Generated from the \`recipes/*.json\` ladder. Do not edit this list by hand.

${rows.join('\n')}`
}

function replaceGeneratedBlock(current, startMarker, endMarker, content, fileLabel) {
  const startIndex = current.indexOf(startMarker)
  const endIndex = current.indexOf(endMarker)

  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
    throw new Error(`${fileLabel} is missing generated recipe markers`)
  }

  return [
    current.slice(0, startIndex + startMarker.length),
    '\n',
    content.trimEnd(),
    '\n',
    current.slice(endIndex),
  ].join('')
}

async function writeIfChanged(filePath, content) {
  await mkdir(path.dirname(filePath), { recursive: true })
  const current = (await pathExists(filePath)) ? await readFile(filePath, 'utf8') : null
  if (current !== content) {
    await writeFile(filePath, content)
  }
}

async function checkFile(filePath, expectedContent) {
  if (!(await pathExists(filePath))) {
    return `${path.relative(root, filePath)} is missing`
  }

  const current = await readFile(filePath, 'utf8')
  if (current !== expectedContent) {
    return `${path.relative(root, filePath)} is out of date`
  }

  return null
}

async function main() {
  const checkOnly = process.argv.includes('--check')
  const features = await loadFeatures()
  const recipes = await loadRecipes()
  const featureMap = new Map(features.map(({ manifest }) => [manifest.name, manifest]))
  const readmePath = path.join(root, 'README.md')
  const readme = await readFile(readmePath, 'utf8')

  const outputs = [
    {
      filePath: path.join(root, 'docs', 'features', 'index.md'),
      content: renderFeatureIndex(features),
    },
    {
      filePath: path.join(root, 'docs', 'recipes', 'index.md'),
      content: renderRecipeIndex(recipes, featureMap),
    },
    {
      filePath: readmePath,
      content: replaceGeneratedBlock(
        readme,
        readmeRecipeStart,
        readmeRecipeEnd,
        renderReadmeRecipeList(recipes, featureMap),
        'README.md'
      ),
    },
  ]

  if (checkOnly) {
    const errors = (await Promise.all(
      outputs.map((output) => checkFile(output.filePath, output.content))
    )).filter(Boolean)

    if (errors.length > 0) {
      console.error('Generated documentation is out of date. Run npm run docs:generate.')
      for (const error of errors) {
        console.error(`- ${error}`)
      }
      process.exit(1)
    }

    console.log('Generated documentation is up to date')
    return
  }

  for (const output of outputs) {
    await writeIfChanged(output.filePath, output.content)
  }

  console.log('Generated docs/features/index.md')
  console.log('Generated docs/recipes/index.md')
}

await main()
